version: '3'
services:
  nginx:
   container_name: app-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

app-mysql:
   container_name: app-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_USER: root
    MYSQL_DATABASE: cicd_post_db
    MYSQL_PASSWORD: Test@Data@321
    MYSQL_ROOT_PASSWORD: Test@Data@321
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  app:
    image: arunds/springboot-data-docker-mysql-app:0.0.1-SNAPSHOT
    restart: always
    working_dir: /posts
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:  
      - app-nginx
      - app-mysql   